version: 2.1
setup: true

orbs:
  test-harness: govstack-working-group/testutils@dev:6aff0fe7c95df6969ef0ad7163a937fa7c1b74e9

workflows:
  test_everything:
    jobs:
      - test-harness/create-config:
          post-steps: # Persist to workspace has to be defined in main workflow
            - persist_to_workspace:
                root: workspace
                paths:
                  - generated.yml
      - test-harness/execute-tests:
          requires:
            - test-harness/create-config

