version: '3.3'

services:
  test-app:
    image: digital-registries-image
    ports:
      - 3333:3001
      - 4422:4422
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./mockoon-digitalregistries.json:/mockoon-digitalregistries.json
