version: '3.3'

services:
  app:
    image: digital-registries-image
    ports:
      - 3333:3001
    networks:
      - web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./mockoon-digitalregistries.json:/mockoon-digitalregistries.json


networks:
  web:
    driver: bridge